# Generated by Django 3.2.4 on 2021-06-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Father_name', models.CharField(max_length=255)),
                ('Experience', models.IntegerField(blank=True)),
                ('Age', models.IntegerField(blank=True)),
                ('Phone', models.CharField(max_length=14)),
            ],
        ),
    ]
