# Generated by Django 3.2.4 on 2021-07-06 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Surname', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Father_name', models.CharField(max_length=255)),
                ('Photo', models.ImageField(null=True, upload_to='photos')),
                ('Experience', models.IntegerField(blank=True)),
                ('Age', models.IntegerField(blank=True)),
                ('Phone', models.CharField(max_length=14, null=True)),
                ('Bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Актеры театра',
                'verbose_name_plural': 'Актеры театра',
                'ordering': ['Surname', 'Name'],
            },
        ),
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Director', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.IntegerField()),
                ('Place', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Staging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theatre.plays')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Surname', models.CharField(max_length=255)),
                ('Client_Name', models.CharField(max_length=255)),
                ('Client_Phone', models.CharField(max_length=14, null=True)),
                ('Ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theatre.tickets')),
            ],
        ),
        migrations.CreateModel(
            name='Amplua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=255)),
                ('Actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theatre.actors')),
                ('Play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theatre.plays')),
            ],
        ),
    ]
