# Generated by Django 3.2.4 on 2021-06-18 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Theatre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amplua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=255)),
                ('Actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theatre.actors')),
            ],
        ),
    ]
