# Generated by Django 3.2.4 on 2021-07-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theatre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plays',
            name='About',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='plays',
            name='Picture',
            field=models.ImageField(null=True, upload_to='photos', verbose_name='Афиша'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='Age',
            field=models.IntegerField(blank=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='Bio',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='Experience',
            field=models.IntegerField(blank=True, verbose_name='Стаж'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='Father_name',
            field=models.CharField(max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='Name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='Phone',
            field=models.CharField(max_length=14, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='Photo',
            field=models.ImageField(null=True, upload_to='photos', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='actors',
            name='Surname',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='plays',
            name='Author',
            field=models.CharField(max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='plays',
            name='Director',
            field=models.CharField(max_length=255, verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='plays',
            name='Title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
