# Generated by Django 3.2.4 on 2021-06-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theatre', '0002_amplua'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='Bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
