# Generated by Django 3.2.4 on 2021-07-07 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theatre', '0002_auto_20210707_0437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amplua',
            options={'ordering': ['Role'], 'verbose_name': 'Амплуа актера', 'verbose_name_plural': 'Амплуа актеров'},
        ),
        migrations.AlterModelOptions(
            name='plays',
            options={'ordering': ['Title'], 'verbose_name': 'Пьеса', 'verbose_name_plural': 'Пьесы'},
        ),
        migrations.AlterModelOptions(
            name='staging',
            options={'verbose_name': 'Постановка', 'verbose_name_plural': 'Постановки'},
        ),
        migrations.AlterModelOptions(
            name='tickets',
            options={'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.AlterField(
            model_name='staging',
            name='Date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
