# Generated by Django 3.2.4 on 2021-06-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Theatre', '0003_actors_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actors',
            options={'ordering': ['Surname', 'Name'], 'verbose_name': 'Актеры театра', 'verbose_name_plural': 'Актеры театра'},
        ),
        migrations.AddField(
            model_name='actors',
            name='Photo',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
